# Generated by Django 4.2.7 on 2024-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarcopenia", "0003_data_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="probability",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
