# Generated by Django 5.0.4 on 2024-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarcopenia", "0004_alter_data_probability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="data",
            name="working_Status",
        ),
        migrations.AddField(
            model_name="data",
            name="asthma",
            field=models.CharField(
                choices=[("0.0", "No"), ("1.0", "Yes")], max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="diabetes_mellitus",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")], max_length=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="hypertension",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")], max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="alcohol",
            field=models.CharField(
                choices=[("0", "None"), ("social", "Social"), ("regular", "Regular")],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="education",
            field=models.CharField(
                choices=[
                    ("primary school", "Primary School"),
                    ("high school", "High School"),
                    ("university", "University"),
                    ("other", "Other"),
                    ("illiterate", "None"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="exercise",
            field=models.CharField(
                choices=[
                    ("0", "None"),
                    ("1-2/week", "1 - 2 Per Week"),
                    ("3-4/week", "3 - 4 Per Week"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="gender",
            field=models.CharField(
                choices=[("0", "Female"), ("1", "Male")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="smoking",
            field=models.CharField(
                choices=[("0.0", "No"), ("1.0", "Yes")], max_length=10
            ),
        ),
        migrations.AddField(
            model_name="data",
            name="working_status",
            field=models.CharField(
                choices=[
                    ("retired", "Retired"),
                    ("working", "Working"),
                    ("unemployed", "Unemployed"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
