# Generated by Django 5.0.4 on 2024-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sarcopenia",
            "0005_remove_data_occupation_remove_data_working_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_grip_strength",
                    models.CharField(
                        choices=[("0.0", "No"), ("1.0", "Yes")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("grip_strength", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_contraction_stress",
                    models.CharField(
                        choices=[("0.0", "No"), ("1.0", "Yes")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("contraction_stress", models.FloatField()),
                ("gait_speed", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="data",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], max_length=1
            ),
        ),
    ]
