# Generated by Django 5.0.4 on 2024-04-23 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sarcopenia", "0006_modelthree_modeltwo_alter_data_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelThree",
        ),
        migrations.DeleteModel(
            name="ModelTwo",
        ),
    ]
