# Generated by Django 5.0.4 on 2024-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sarcopenia", "0007_delete_modelthree_delete_modeltwo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="gender",
            field=models.CharField(
                choices=[("0", "Female"), ("1", "Male")], max_length=1
            ),
        ),
    ]
