# Generated by Django 5.0.4 on 2024-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sarcopenia",
            "0009_alter_data_options_data_additional_data_required_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="probability",
            new_name="probability_model1",
        ),
        migrations.AddField(
            model_name="data",
            name="probability_model2",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="data",
            name="probability_model3",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
